### ISSUE TITLE
Minor error when verifiying if the pad is symmetrical

### ISSUE THREAD

**Issue by rodrigodebem** [ecoto/dagnn_caffe_deploy#1]
Minor mistake at line [181](https://github.com/ecoto/dagnn_caffe_deploy/blob/master/dagnn_caffe_deploy.m#L181) :

`if any(net.layers{idx}.block.pad([1, 3]) ~= net.layers{idx}.block.pad([2, 3]))`

I suppose it should be

`if any(net.layers{idx}.block.pad([1, 3]) ~= net.layers{idx}.block.pad([2, 4]))`

to compare TOP vs. BOTTOM and LEFT vs. RIGHT.

[]s,
Rodrigo.

**Comment by ecoto** [comment]
Fixed in development branch
